/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppValuationRouteImport } from './routes/app.valuation'
import { Route as AppRiskScannerRouteImport } from './routes/app.risk-scanner'
import { Route as AppOptimizationRouteImport } from './routes/app.optimization'
import { Route as AppExitScoreRouteImport } from './routes/app.exit-score'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppValuationRoute = AppValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskScannerRoute = AppRiskScannerRouteImport.update({
  id: '/risk-scanner',
  path: '/risk-scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizationRoute = AppOptimizationRouteImport.update({
  id: '/optimization',
  path: '/optimization',
  getParentRoute: () => AppRoute,
} as any)
const AppExitScoreRoute = AppExitScoreRouteImport.update({
  id: '/exit-score',
  path: '/exit-score',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/exit-score': typeof AppExitScoreRoute
  '/app/optimization': typeof AppOptimizationRoute
  '/app/risk-scanner': typeof AppRiskScannerRoute
  '/app/valuation': typeof AppValuationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/exit-score': typeof AppExitScoreRoute
  '/app/optimization': typeof AppOptimizationRoute
  '/app/risk-scanner': typeof AppRiskScannerRoute
  '/app/valuation': typeof AppValuationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/exit-score': typeof AppExitScoreRoute
  '/app/optimization': typeof AppOptimizationRoute
  '/app/risk-scanner': typeof AppRiskScannerRoute
  '/app/valuation': typeof AppValuationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/dashboard'
    | '/app/exit-score'
    | '/app/optimization'
    | '/app/risk-scanner'
    | '/app/valuation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/dashboard'
    | '/app/exit-score'
    | '/app/optimization'
    | '/app/risk-scanner'
    | '/app/valuation'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/dashboard'
    | '/app/exit-score'
    | '/app/optimization'
    | '/app/risk-scanner'
    | '/app/valuation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/valuation': {
      id: '/app/valuation'
      path: '/valuation'
      fullPath: '/app/valuation'
      preLoaderRoute: typeof AppValuationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk-scanner': {
      id: '/app/risk-scanner'
      path: '/risk-scanner'
      fullPath: '/app/risk-scanner'
      preLoaderRoute: typeof AppRiskScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/optimization': {
      id: '/app/optimization'
      path: '/optimization'
      fullPath: '/app/optimization'
      preLoaderRoute: typeof AppOptimizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exit-score': {
      id: '/app/exit-score'
      path: '/exit-score'
      fullPath: '/app/exit-score'
      preLoaderRoute: typeof AppExitScoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExitScoreRoute: typeof AppExitScoreRoute
  AppOptimizationRoute: typeof AppOptimizationRoute
  AppRiskScannerRoute: typeof AppRiskScannerRoute
  AppValuationRoute: typeof AppValuationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExitScoreRoute: AppExitScoreRoute,
  AppOptimizationRoute: AppOptimizationRoute,
  AppRiskScannerRoute: AppRiskScannerRoute,
  AppValuationRoute: AppValuationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
